import {StyleMetrics, LineEdit} from "std-widgets.slint";

export component ComboBox inherits Rectangle {
    in-out property <string> value;
    in property <[string]> choices;
    height: 32px;

    text := LineEdit {
        horizontal-alignment: left;
        width: 100%;
        height: 100%;
    }

    i := Image {
        source: @image-url("../assets/icons/down.svg");
        colorize: StyleMetrics.textedit-text-color;
        height: 40%;
        width: self.height;
        image-fit: contain;
        x: parent.width - self.width - self.y;
        y: (parent.height - self.height)/2;
    }

    TouchArea {
        clicked => { popup.show(); }

        width: 100%;
        height: 100%;
    }

    popup := PopupWindow {
        x:0;
        y: root.height;
        width: root.width;

        Rectangle {
            background: StyleMetrics.window-background;
            border-radius: 3px;
            border-width: 2px;
            border-color: StyleMetrics.textedit-text-color-disabled;
        }

        VerticalLayout {
            spacing: 6px;
            padding: 3px;

            for value[idx] in root.choices: Rectangle {
                border-radius: 3px;
                background: item-area.has-hover ? StyleMetrics.textedit-background-disabled : #0000;

                HorizontalLayout {
                    Text {
                        text: value;
                        color: item-area.has-hover ? StyleMetrics.textedit-text-color : StyleMetrics.textedit-text-color.darker(0.5);
                        font-size: 14px;
                    }
                }

                item-area := TouchArea {
                    clicked => {
                        root.value = value;
                    }
                }
            }
        }
    }
}