[package]
name = "test-slint"
version = "0.1.0"
authors = ["maotovisk <me@maot.dev>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.3.2"

[build-dependencies]
slint-build = "1.0"
